### ISSUE TITLE
Representation issue for 4-digit starting with "1"

### ISSUE THREAD

**Issue by trizen** [burak/CPAN-Lingua-TR-Numbers#1]
Hi. There seems to be a minor issue in the representation of 4-digit numbers that begin with `1`.

For example `1168` is represented as `"bir bin yüz altmış sekiz"` instead of `"bin yüz altmış sekiz"`.

See the discussion on this issue at: https://oeis.org/history?seq=A305100

**Comment by burak** [comment]
Release v0.35 with the patch.
